### ISSUE TITLE
Demise: function: Demise_tagged not working 

### ISSUE THREAD

**Issue by JangoBritt** [JangoBritt/ACS6#45]
I switched on the command block for Demise, and it ran successfully, but didn't give me the DJT tag.

This urgently needs testing!

I think it's because you're using @s instead of @a ?

`execute as @s[name="JangoBritt",tag=!DJT] run tag @s add DJT`

Wouldn't that execute as the command block, and not as the player?

**Comment by JangoBritt** [comment]
Fixed.

**Comment by tonystar73** [comment]
How did you fix this?

**Comment by JangoBritt** [comment]
I changed the ` execute as @s` into `execute as @a` on the functions files

**Comment by tonystar73** [comment]
Can we change that back please? The @a would run for everyone, when the funciton should only run on the individual that it's checking for.

**Comment by JangoBritt** [comment]
no... `execute as @a[name="TonyStar73"]`

**Comment by tonystar73** [comment]
If you want, have the commmand block run a `execute as @a ...` before the function use.
