### ISSUE TITLE
FarmersDelight: Upcoming identifier changes

### ISSUE THREAD

**Issue by JangoBritt** [JangoBritt/ACS6#46]
Moaswies said that the wild crops are going to be changing identifiers in the next update... so existing ones will turn into update blocks.

I'm trying to see if they can update it smoothly... otherwise, I may just remove the feature_rules for them in the meantime, so there aren't too many spawned in the world

**Comment by tonystar73** [comment]
I wonder why they feel a need to change the identifier for?

**Comment by JangoBritt** [comment]
It was related to the upcoming changes in 1.21.10 that will move Holiday Creator Features into Vanilla. There are some changes that the mod makers need to take into account, regarding custom components, and scripting, and I've been making sure that all our mods are already compatible, or at least in the process.

**Comment by tonystar73** [comment]
I see... fair enough.

**Comment by JangoBritt** [comment]
I've modified all the wild crops in the legacy version to match the block names in the upcoming version for 1.21.20, so that they will seamlessly translate. This allows us to re-enable the feature_rule that spawns the wild crops
#77
