### ISSUE TITLE
Farmers Delight Cooking Pan Duplicating Items

### ISSUE THREAD

**Issue by tonystar73** [JangoBritt/ACS6#48]
I was chatting with the Eagle Alliance lot before going to bed, and I overheard Rez had found some kind of bug where he's able to making an infinite amount of cooked beef.

I'm not certain if this is something we had covered or not... But I had asked them to not abuse the bug too much, since it is a bug that needs to be fixed.

**Comment by JangoBritt** [comment]
Skillet Entity Script deleted
