### ISSUE TITLE
Farmers Delight Cooking Pot Error

### ISSUE THREAD

**Issue by tonystar73** [JangoBritt/ACS6#49]
I was chatting with the Eagle Alliance lot before going to bed, and whilst discussing another bug issue, bigdog pointed out a bug on his discord stream, where he's able to pull out some kind of Fire Fuel item? that is used with the cooking pot as it's fuel.

They can't seem to use the item or place it in any way, but it's something they can obtain, which probably shouldn't be possible.

**Comment by JangoBritt** [comment]
This is only possible if you put a hopper under a cooking pot, which is pointless, because it won't pull out the completed item anyway. I've fed this back to the developer
