### ISSUE TITLE
Mail Box Empty After Package Sent

### ISSUE THREAD

**Issue by Purplelady1022** [JangoBritt/ACS6#61]
I was told I was sent mail, but when I checked my Mail Box (which I have received mail in previously), there was nothing there. It was tried to send me several times with no luck. I went to break and move my mail box (to see if that helped) and when I did the 3 packages that had been sent to me dropped. Not sure what was going on, but if someone indicates they sent you something and it's not there, you might try breaking your Mail Box.

**Comment by JangoBritt** [comment]
#64 I think I've got this fixed. Mailboxes will need to be re-created once, to remove the old container entity
