### ISSUE TITLE
Mail Boxes not prompting to name them

### ISSUE THREAD

**Issue by tonystar73** [JangoBritt/ACS6#74]
The following Mail Boxes do not prompt you to name them, causing them to not appear on the list when send mail via the Post Box.

- Stripped Dark Oak Mail Box
- Dark Oak Mail Box
- Dark Oak MailBox

![Minecraft 05_07_2024 03_13_25](https://github.com/JangoBritt/ACS6/assets/34952416/dbc2c9aa-fe7c-4f2a-8cc0-9a18bb95ffe4)

**Comment by JangoBritt** [comment]
#76
