### ISSUE TITLE
Workbench - Fences

### ISSUE THREAD

**Issue by EMPRESSTlTAN** [JangoBritt/ACS6#75]
Y'ello!! Titan here~~
When I went to create a fence using the workbench on 7/5/2024 I found a bit of a problem. Due to the name of the fence posts used to craft the fence, I cannot make the fence. For example, if I tried to make a "Cherry Fence", the ingredient calls for a "Cherry Wood Post" and I just have a "Cherry Fence" both of these products look the exact same - the names are just different. When trying to make the "Cherry Fence" in the workbench was not allowed to. Even when putting in the items one at a time, 

I know this explanation is confusing; I have attached screenshots to show you. 
![Screenshot 2024-07-05 204031](https://github.com/JangoBritt/ACS6/assets/174843576/dc9f2add-a01d-4336-a7c1-ef3568ba370c)
![Screenshot 2024-07-05 204047](https://github.com/JangoBritt/ACS6/assets/174843576/54bedd1e-da3d-4164-aca5-13c71e20c761)
![Screenshot 2024-07-05 204436](https://github.com/JangoBritt/ACS6/assets/174843576/0418b6ab-dedf-4d5e-9438-30e929c603c8)

**Comment by JangoBritt** [comment]
Posts are cut in a stonecutter, for some reason.
